name: 'BiblePlugin'
version: @version@
main: me.thevipershow.bibleplugin.BiblePlugin
api-version: '1.13'
authors: [TheViperShow]
description: 'A Minecraft plugin to interact with the sacred text.'
commands:
  bible:
    description: 'Interact with the bible'
    permission: 'bible.commands'
    permission-message: '§8[§eBiblePlugin§8]§f: §7You are missing permissions!'
    usage: |
      §7Get all available bibles.
      - §8/<§ecommand§8> available
      §7Get all downloaded bibles.
      - §8/<§ecommand§8> downloaded
      §7Download a new bible.
      - §8/<§ecommand§8> download §8[§ebible§8]
      §7Get a verse from a bible.
      - §8/<§ecommand§8> verse §8[§ebible§8] §8[§echapter§7:verse§8]
      §7Get the occurrences of a word in a bible.
      - §8/<§ecommand§8> occurrences §8[§ebible§8] §8[§eword§8]
      §7Get the verses where that contain a word or phrase in a bible.
      - §8/<§ecommand§8> find §8[§ebible§8] §8[§eword§8]